### ISSUE TITLE
Unfollow crashing without unfollowing anybody

### ISSUE THREAD

**Issue by yondermann** [alexal1/Insomniac#315]
Hi,
Unfollow doesn't work this is the command I use:
py start.py --unfollow-followed-by-anyone --unfollow 30-60 --repeat 160-220 --no-speed-check

On the phone the unfollow window pops up but nothing happens on the screen. The log says "Next item not found: probably reached end of the screen".
Then it comes a crash and Instagram closes and starts from the beginning again.

I run the lates version of insomniac

[Crash-2021-04-09-09-16-27.zip](https://github.com/alexal1/Insomniac/files/6283852/Crash-2021-04-09-09-16-27.zip)
[Crash-2021-04-09-09-15-39.zip](https://github.com/alexal1/Insomniac/files/6283853/Crash-2021-04-09-09-15-39.zip)
[Crash-2021-04-09-09-14-55.zip](https://github.com/alexal1/Insomniac/files/6283854/Crash-2021-04-09-09-14-55.zip)
[Crash-2021-04-09-09-14-36.zip](https://github.com/alexal1/Insomniac/files/6283855/Crash-2021-04-09-09-14-36.zip)
[Crash-2021-04-09-09-13-59.zip](https://github.com/alexal1/Insomniac/files/6283856/Crash-2021-04-09-09-13-59.zip)
[Crash-2021-04-09-09-13-41.zip](https://github.com/alexal1/Insomniac/files/6283857/Crash-2021-04-09-09-13-41.zip)

**Comment by yondermann** [comment]
Is any news on this issue @alexal1 ? 
I've seen various others reporting unfollow issues but no response to any of those either.

**Comment by yondermann** [comment]
I scripts still can't unfollow anybody. I've updated to the latest version but the same problem persist. Am I the only one who can't make this work?

**Comment by roncam82** [comment]
The script is not unfollowing anybody

**Comment by muzzol** [comment]
I've tried with some older versions: 176.0.0.38.116  179.0.0.26.132

it gets stuck in confirmation window

![screenshot](https://user-images.githubusercontent.com/6727358/117961107-063d3f00-b31e-11eb-8382-a4b6f9173d13.jpg)

**Comment by yondermann** [comment]
I've run the 3.7.11 version and the same problem still persist. It doesn't get past the unfollow confirmation window.

[Crash-2021-05-12-16-06-15.zip](https://github.com/alexal1/Insomniac/files/6466700/Crash-2021-05-12-16-06-15.zip)
[Crash-2021-05-12-16-05-57.zip](https://github.com/alexal1/Insomniac/files/6466701/Crash-2021-05-12-16-05-57.zip)
[Crash-2021-05-12-16-05-06.zip](https://github.com/alexal1/Insomniac/files/6466702/Crash-2021-05-12-16-05-06.zip)
[Crash-2021-05-12-16-04-12.zip](https://github.com/alexal1/Insomniac/files/6466703/Crash-2021-05-12-16-04-12.zip)
[Crash-2021-05-12-16-03-22.zip](https://github.com/alexal1/Insomniac/files/6466704/Crash-2021-05-12-16-03-22.zip)
[Crash-2021-05-12-16-03-03.zip](https://github.com/alexal1/Insomniac/files/6466705/Crash-2021-05-12-16-03-03.zip)
[Crash-2021-05-12-16-02-48.zip](https://github.com/alexal1/Insomniac/files/6466707/Crash-2021-05-12-16-02-48.zip)
[Crash-2021-05-12-16-02-31.zip](https://github.com/alexal1/Insomniac/files/6466708/Crash-2021-05-12-16-02-31.zip)
[Crash-2021-05-12-16-02-15.zip](https://github.com/alexal1/Insomniac/files/6466709/Crash-2021-05-12-16-02-15.zip)

**Comment by yondermann** [comment]
I moved insomniac to a raspberry pi to see if that changes anything but nothing changed. The unfollow button is still not tapped.

**Comment by yondermann** [comment]
For anyone who is having similar problems.
I used a nexus5 with its latest android and instagram app. I swapped to a oneplus one with lineageOS 16 which is Android9 and the problem disappeared. 
Everything works as expected now.

**Comment by alexal1** [comment]
Fixed in `v3.7.14`

**Comment by yondermann** [comment]
I've just updated to give it a try again on Android 6.0.1 but it still doesn't work.
